server:
  port: ${LOCAL_SERVER_PORT}
spring:
  application:
    name: matchingfit

  profiles:
    active: ${PROFILE:matchingfit}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
            scope: profile_nickname, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "${custom.site.backUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jpa:
    hibernate:
      ddl-auto: update # 개발 시에는 update, 운영 시에는 none or validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true # 콘솔에 SQL 출력 (운영에서는 false 추천)
    open-in-view: false # JPA Lazy 로딩 시 메모리 누수 방지
  data:
    redis:
      host: redis
      port: 6379
    elasticsearch:
      uris: http://${ES_LOCAL_HOST}:${ES_LOCAL_PORT}              # ES 서버 주소(여러 개라면 ,로 구분)
      #username: your_username                  # 계정 필요 없다면 주석
      #password: your_password                  # 계정 필요 없다면 주석
  sql:
    init:
      mode: always               # schema.sql, data.sql 자동 실행 여부
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:5173"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: ""
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "BLOG DEV"
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
  jwt:
    secretKey: ${JWT_SECRET_KEY}
  accessToken:
    expirationSeconds: 86400

openai:
  api:
    key: ${OPENAI_SECRET_KEY} # 실제 발급받은 키 입력

cookie:
  domain: "localhost"
