spring:
  application:
    name: matchingfit

  profiles:
    active: ${PROFILE:matchingfit}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update            # 개발 시에는 update, 운영 시에는 none or validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true           # 콘솔에 SQL 출력 (운영에서는 false 추천)
    open-in-view: false          # JPA Lazy 로딩 시 메모리 누수 방지

  sql:
    init:
      mode: always               # schema.sql, data.sql 자동 실행 여부

  data:
    elasticsearch:
      uris: http://${ES_LOCAL_HOST}:${ES_LOCAL_PORT}              # ES 서버 주소(여러 개라면 ,로 구분)
      #username: your_username                  # 계정 필요 없다면 주석
      #password: your_password                  # 계정 필요 없다면 주석